//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork_19_20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string NameManufacturer { get; set; }
        public Nullable<int> WareMo { get; set; }
        public Nullable<int> WareTu { get; set; }
        public Nullable<int> WareWe { get; set; }
        public Nullable<int> WareTh { get; set; }
        public Nullable<int> WareFr { get; set; }
        public Nullable<int> WareSa { get; set; }
        public Nullable<int> WareSu { get; set; }
        public string Gild { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
